@TherapyCenter2_HostAddress = https://localhost:7093

GET {{TherapyCenter2_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{TherapyCenter2_HostAddress}}/api/appointment

###

POST {{TherapyCenter2_HostAddress}}/api/appointment
Content-Type: application/json

{
  //AppointmentCreateDto
}

###

@id=0
DELETE {{TherapyCenter2_HostAddress}}/api/appointment/{{id}}

###

GET {{TherapyCenter2_HostAddress}}/api/appointment/{{id}}

###

PUT {{TherapyCenter2_HostAddress}}/api/appointment/{{id}}
Content-Type: application/json

{
  //AppointmentUpdateDto
}

###

PUT {{TherapyCenter2_HostAddress}}/api/appointment/{{id}}/cancel

###

PUT {{TherapyCenter2_HostAddress}}/api/appointment/{{id}}/complete

###

POST {{TherapyCenter2_HostAddress}}/api/auth/login
Content-Type: application/json

{
  //LoginDto
}

###

POST {{TherapyCenter2_HostAddress}}/api/auth/register
Content-Type: application/json

{
  //RegisterDto
}

###

GET {{TherapyCenter2_HostAddress}}/api/doctor

###

POST {{TherapyCenter2_HostAddress}}/api/doctor
Content-Type: application/json

{
  //CreateDoctorDto
}

###

DELETE {{TherapyCenter2_HostAddress}}/api/doctor/{{id}}

###

PUT {{TherapyCenter2_HostAddress}}/api/doctor/{{id}}
Content-Type: application/json

{
  //UpdateDoctorDto
}

###

GET {{TherapyCenter2_HostAddress}}/api/doctorfinding

###

POST {{TherapyCenter2_HostAddress}}/api/doctorfinding
Content-Type: application/json

{
  //CreateDoctorFindingDto
}

###

@appointmentId=0
GET {{TherapyCenter2_HostAddress}}/api/doctorfinding/appointment/{{appointmentId}}

###

DELETE {{TherapyCenter2_HostAddress}}/api/doctorfinding/{{id}}

###

GET {{TherapyCenter2_HostAddress}}/api/doctorfinding/{{id}}

###

PUT {{TherapyCenter2_HostAddress}}/api/doctorfinding/{{id}}
Content-Type: application/json

{
  //UpdateDoctorFindingDto
}

###

POST {{TherapyCenter2_HostAddress}}/api/payment/create_order
Content-Type: application/json

{
  //CreateOrderDto
}

###

POST {{TherapyCenter2_HostAddress}}/api/slot
Content-Type: application/json

{
  //CreateSlotDto
}

###

@doctorId=0
GET {{TherapyCenter2_HostAddress}}/api/slot/doctor/{{doctorId}}

###

DELETE {{TherapyCenter2_HostAddress}}/api/slot/{{id}}

###

PUT {{TherapyCenter2_HostAddress}}/api/slot/{{id}}
Content-Type: application/json

{
  //UpdateSlotDto
}

###

POST {{TherapyCenter2_HostAddress}}/api/therapy
Content-Type: application/json

{
  //CreateTherapyDto
}

###

PUT {{TherapyCenter2_HostAddress}}/api/therapy/{{id}}
Content-Type: application/json

{
  //UpdateTherapyDto
}

###

GET {{TherapyCenter2_HostAddress}}/api/therapy

###

DELETE {{TherapyCenter2_HostAddress}}/api/therapy/{{id}}

###

GET {{TherapyCenter2_HostAddress}}/api/therapy/{{id}}

###
