@TherapyCenter2_HostAddress = https://localhost:7093

POST {{TherapyCenter2_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "firstName": "sneha",
  "lastName": "kashyap",
  "email": "sneha@example.com",
  "password": "sneha@1234",
  "role": "Patient",
  "phoneNumber": "8967452378"
}







GET {{TherapyCenter2_HostAddress}}/api/appointment/my

###

### Get My Appointments
GET https://localhost:7093/api/appointment/my
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhhckBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJQYXRpZW50IiwiZXhwIjoxNzc3MjcyNDQ2LCJpc3MiOiJUaGVyYXB5Q2VudGVyIiwiYXVkIjoiVGhlcmFweUNlbnRlclVzZXJzIn0.d_dr2-quXj1YxWO5BZC15Wmv9o5sjuGlnVC9r6Er5ok
###

GET {{TherapyCenter2_HostAddress}}/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiaGFyc2hAdGhlcmFweS5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3NzQzNzYxNSwiaXNzIjoiVGhlcmFweUNlbnRlciIsImF1ZCI6IlRoZXJhcHlDZW50ZXJVc2VycyJ9.Q6p7Oqt_kEqiZopE4JGIqJ5BXQVzeqMfqsymp2HFRso
###
